services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile.server
    container_name: lab_server
    ports:
      - "12345:12345"
    networks:
      - lab_network
    volumes:
      - ./.env:/laba/.env:ro

  postgres:
    image: postgres:16-alpine
    container_name: studygroup_db
    environment:
      POSTGRES_DB: studygroup_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lab_network

  client:
    build:
      context: .
      dockerfile: client/Dockerfile.client
    container_name: lab_client_1
    depends_on:
      - server
    networks:
      - lab_network
    stdin_open: true
    tty: true

networks:
  lab_network:
    driver: bridge

volumes:
  postgres_data: