FROM eclipse-temurin:17-jdk-alpine
WORKDIR /laba
COPY target/classes /laba/classes
COPY target/lib /laba/lib
COPY src/main/resources/logging.properties /laba/logging.properties
CMD ["java", \
     "-Djava.security.egd=file:/dev/./urandom", \
     "-Djava.util.logging.config.file=/laba/logging.properties", \
     "-XX:+UnlockExperimentalVMOptions", \
     "-XX:+UseContainerSupport", \
     "-cp", "/laba/classes:/laba/lib/*", \
     "com.example.Server.Server"]