package com.example;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
public class LocalizationManager {
    private static final Map<String, String> RU = new HashMap<>();
    private static final Map<String, String> CS = new HashMap<>();
    private static final Map<String, String> DA = new HashMap<>();
    private static final Map<String, String> ES_CO = new HashMap<>();
    public static LocalizationManager instance;
    private Map<String, String> currentLocation;
    private Locale currentLocale;
    static {
        RU.put("auth.title", "Авторизация");
        RU.put("auth.login", "Логин");
        RU.put("auth.choose.lang", "Язык");
        RU.put("auth.password", "Пароль");
        RU.put("auth.login.in", "Войти");
        RU.put("auth.register.in", "Зарегистрироваться");
        RU.put("auth.error", "Неверный логин или пароль");
        RU.put("auth.success", "Успешный вход");
        RU.put("auth.registered", "Регистрация успешна");
        RU.put("auth.empty_fields", "Заполните все поля");
        RU.put("auth.connecting", "Подключение...");
        RU.put("main.title", "Управление коллекцией");
        RU.put("main.user", "Пользователь");
        RU.put("main.refresh", "Обновить");
        RU.put("main.add", "Добавить");
        RU.put("main.clear", "Очистить");
        RU.put("main.remove", "Удалить");
        RU.put("main.update", "Изменить");
        RU.put("main.show", "Показать все");
        RU.put("main.lang", "Язык");
        RU.put("main.exit", "Выход");
        RU.put("main.filter", "Фильтр");
        RU.put("table.id", "ID");
        RU.put("table.name", "Название");
        RU.put("table.x", "X");
        RU.put("table.y", "Y");
        RU.put("table.students", "Студенты");
        RU.put("table.expelled", "Отчислены");
        RU.put("table.form", "Форма обучения");
        RU.put("table.semester", "Семестр");
        RU.put("table.admin", "Админ");
        RU.put("table.owner", "Владелец");
        RU.put("error.network", "Ошибка соединения с сервером");
        RU.put("error.server", "Ошибка сервера");
        CS.put("auth.title", "Autorizace");
        CS.put("auth.login", "Přihlášení");
        CS.put("auth.password", "Heslo");
        CS.put("auth.login.in", "Přihlásit");
        CS.put("auth.register.in", "Registrovat");
        CS.put("auth.error", "Nesprávné přihlášení nebo heslo");
        CS.put("auth.success", "Úspěšné přihlášení");
        CS.put("auth.choose.lang", "Jazyk");
        CS.put("auth.registered", "Registrace úspěšná");
        CS.put("auth.empty_fields", "Vyplňte všechna pole");
        CS.put("auth.connecting", "Připojování...");
        CS.put("main.title", "Správa kolekce");
        CS.put("main.user", "Uživatel");
        CS.put("main.refresh", "Obnovit");
        CS.put("main.add", "Přidat");
        CS.put("main.clear", "Vyčistit");
        CS.put("main.remove", "Odstranit");
        CS.put("main.update", "Upravit");
        CS.put("main.show", "Zobrazit vše");
        CS.put("main.lang", "Jazyk");
        CS.put("main.exit", "Ukončit");
        CS.put("main.filter", "Filtr");
        CS.put("table.id", "ID");
        CS.put("table.name", "Název");
        CS.put("table.x", "X");
        CS.put("table.y", "Y");
        CS.put("table.students", "Studenti");
        CS.put("table.expelled", "Vyloučeni");
        CS.put("table.form", "Forma vzdělávání");
        CS.put("table.semester", "Semestr");
        CS.put("table.admin", "Správce");
        CS.put("table.owner", "Vlastník");
        CS.put("error.network", "Chyba připojení k serveru");
        CS.put("error.server", "Chyba serveru");
        DA.put("auth.title", "Autorisation");
        DA.put("auth.login", "Login");
        DA.put("auth.password", "Adgangskode");
        DA.put("auth.login.in", "Log ind");
        DA.put("auth.register.in", "Registrer");
        DA.put("auth.error", "Forkert login eller adgangskode");
        DA.put("auth.success", "Succesfuld login");
        DA.put("auth.registered", "Registrering gennemført");
        DA.put("auth.empty_fields", "Udfyld alle felter");
        DA.put("auth.connecting", "Opretter forbindelse...");
        DA.put("auth.choose.lang", "Sprog");
        DA.put("main.title", "Samlingsstyring");
        DA.put("main.user", "Bruger");
        DA.put("main.refresh", "Opdater");
        DA.put("main.add", "Tilføj");
        DA.put("main.clear", "Ryd");
        DA.put("main.remove", "Slet");
        DA.put("main.update", "Rediger");
        DA.put("main.show", "Vis alle");
        DA.put("main.lang", "Sprog");
        DA.put("main.exit", "Afslut");
        DA.put("main.filter", "Filtrer");
        DA.put("table.id", "ID");
        DA.put("table.name", "Navn");
        DA.put("table.x", "X");
        DA.put("table.y", "Y");
        DA.put("table.students", "Studerende");
        DA.put("table.expelled", "Bortvist");
        DA.put("table.form", "Uddannelsesform");
        DA.put("table.semester", "Semester");
        DA.put("table.admin", "Administrator");
        DA.put("table.owner", "Ejer");
        DA.put("error.network", "Forbindelsesfejl til server");
        DA.put("error.server", "Serverfejl");
        ES_CO.put("auth.title", "Autorización");
        ES_CO.put("auth.login", "Inicio de sesión");
        ES_CO.put("auth.password", "Contraseña");
        ES_CO.put("auth.login.in", "Ingresar");
        ES_CO.put("auth.register.in", "Registrarse");
        ES_CO.put("auth.error", "Inicio de sesión o contraseña incorrectos");
        ES_CO.put("auth.success", "Inicio de sesión exitoso");
        ES_CO.put("auth.registered", "Registro exitoso");
        ES_CO.put("auth.empty_fields", "Complete todos los campos");
        ES_CO.put("auth.connecting", "Conectando...");
        ES_CO.put("auth.choose.lang", "Idioma");
        ES_CO.put("main.title", "Gestión de colección");
        ES_CO.put("main.user", "Usuario");
        ES_CO.put("main.refresh", "Actualizar");
        ES_CO.put("main.add", "Agregar");
        ES_CO.put("main.clear", "Limpiar");
        ES_CO.put("main.remove", "Eliminar");
        ES_CO.put("main.update", "Modificar");
        ES_CO.put("main.show", "Mostrar todo");
        ES_CO.put("main.lang", "Idioma");
        ES_CO.put("main.exit", "Salir");
        ES_CO.put("main.filter", "Filtrar");
        ES_CO.put("table.id", "ID");
        ES_CO.put("table.name", "Nombre");
        ES_CO.put("table.x", "X");
        ES_CO.put("table.y", "Y");
        ES_CO.put("table.students", "Estudiantes");
        ES_CO.put("table.expelled", "Expulsados");
        ES_CO.put("table.form", "Forma de educación");
        ES_CO.put("table.semester", "Semestre");
        ES_CO.put("table.admin", "Administrador");
        ES_CO.put("table.owner", "Propietario");
        ES_CO.put("error.network", "Error de conexión con el servidor");
        ES_CO.put("error.server", "Error del servidor");
        RU.put("main.info", "Информация");
        RU.put("main.history", "История команд");
        RU.put("main.map", "Открыть карту");
        RU.put("main.script", "Выполнить скрипт");
        RU.put("main.sum", "Сумма студентов");
        RU.put("main.yours", "Это не ваш объект!");
        RU.put("main.select", "Выберите объект");
        RU.put("main.confirm_clear", "Удалить все ваши объекты?");
        RU.put("main.confirm_delete", "Удалить объект");
        RU.put("main.collection_type", "Тип коллекции: StudyGroup (HashSet)");
        RU.put("main.total", "Всего объектов: %d");
        RU.put("main.my_objects", "Моих объектов: %d");
        RU.put("main.your_id", "Ваш ID: %d");
        RU.put("main.user_label", "Пользователь: %s");
        RU.put("map.title", "Карта коллекции");
        RU.put("map.refresh", "Обновить");
        RU.put("map.page", "Страница %d из %d");
        RU.put("map.click_hint", "Кликните по домику для информации");
        RU.put("map.your_object", "Ваш объект (двойной клик для редактирования)");
        CS.put("main.info", "Informace");
        CS.put("main.history", "Historie příkazů");
        CS.put("main.map", "Otevřít mapu");
        CS.put("main.script", "Spustit skript");
        CS.put("main.sum", "Součet studentů");
        CS.put("main.yours", "Toto není váš objekt!");
        CS.put("main.select", "Vyberte objekt");
        CS.put("main.confirm_clear", "Smazat všechny vaše objekty?");
        CS.put("main.confirm_delete", "Smazat objekt");
        CS.put("main.collection_type", "Typ kolekce: StudyGroup (HashSet)");
        CS.put("main.total", "Celkem objektů: %d");
        CS.put("main.my_objects", "Mých objektů: %d");
        CS.put("main.your_id", "Vaše ID: %d");
        CS.put("main.user_label", "Uživatel: %s");
        CS.put("map.title", "Mapa kolekce");
        CS.put("map.refresh", "Obnovit");
        CS.put("map.page", "Strana %d z %d");
        CS.put("map.click_hint", "Klikněte na domek pro informace");
        CS.put("map.your_object", "★ Váš objekt (dvojklik pro úpravu)");
        DA.put("main.info", "Information");
        DA.put("main.history", "Kommando historik");
        DA.put("main.map", "Åbn kort");
        DA.put("main.script", "Kør script");
        DA.put("main.sum", "Sum af studerende");
        DA.put("main.yours", "Dette er ikke dit objekt!");
        DA.put("main.select", "Vælg objekt");
        DA.put("main.confirm_clear", "Slet alle dine objekter?");
        DA.put("main.confirm_delete", "Slet objekt");
        DA.put("main.collection_type", "Samlingstype: StudyGroup (HashSet)");
        DA.put("main.total", "Samlet objekter: %d");
        DA.put("main.my_objects", "Mine objekter: %d");
        DA.put("main.your_id", "Dit ID: %d");
        DA.put("main.user_label", "Bruger: %s");
        DA.put("map.title", "Samlingskort");
        DA.put("map.refresh", "Opdater");
        DA.put("map.page", "Side %d af %d");
        DA.put("map.click_hint", "Klik på et hus for information");
        DA.put("map.your_object", "Dit objekt (dobbeltklik for at redigere)");
        ES_CO.put("main.info", "Información");
        ES_CO.put("main.history", "Historial de comandos");
        ES_CO.put("main.map", "Abrir mapa");
        ES_CO.put("main.script", "Ejecutar script");
        ES_CO.put("main.sum", "Suma de estudiantes");
        ES_CO.put("main.yours", "¡Este no es su objeto!");
        ES_CO.put("main.select", "Seleccione objeto");
        ES_CO.put("main.confirm_clear", "¿Borrar todos sus objetos?");
        ES_CO.put("main.confirm_delete", "Borrar objeto");
        ES_CO.put("main.collection_type", "Tipo de colección: StudyGroup (HashSet)");
        ES_CO.put("main.total", "Total de objetos: %d");
        ES_CO.put("main.my_objects", "Mis objetos: %d");
        ES_CO.put("main.your_id", "Su ID: %d");
        ES_CO.put("main.user_label", "Usuario: %s");
        ES_CO.put("map.title", "Mapa de colección");
        ES_CO.put("map.refresh", "Actualizar");
        ES_CO.put("map.page", "Página %d de %d");
        ES_CO.put("map.click_hint", "Haga clic en una casa para información");
        ES_CO.put("map.your_object", "Su objeto (doble clic para editar)");
        RU.put("dialog.add.title", "Добавить группу");
        RU.put("dialog.add.header", "Введите данные новой группы");
        RU.put("dialog.edit.title", "Изменить группу");
        RU.put("dialog.edit.header", "Измените данные группы");
        RU.put("dialog.name", "Название:");
        RU.put("dialog.x", "X (≤225):");
        RU.put("dialog.y", "Y:");
        RU.put("dialog.students", "Студенты (>0):");
        RU.put("dialog.expelled", "Отчислены (>0):");
        RU.put("dialog.form", "Форма:");
        RU.put("dialog.semester", "Семестр:");
        RU.put("dialog.admin_section", "АДМИН");
        RU.put("dialog.admin_name", "Имя админа:");
        RU.put("dialog.weight", "Вес (необяз.):");
        RU.put("dialog.eye_color", "Цвет глаз (GREEN/RED/WHITE/BROWN):");
        RU.put("dialog.hair_color", "Цвет волос (GREEN/BLACK/YELLOW/BROWN):");
        RU.put("dialog.nation", "Страна (GERMANY/FRANCE/INDIA/SOUTH_KOREA):");
        RU.put("dialog.loc_section", "ЛОКАЦИЯ");
        RU.put("dialog.loc_x", "Loc X:");
        RU.put("dialog.loc_y", "Loc Y:");
        RU.put("dialog.loc_z", "Loc Z:");
        RU.put("dialog.loc_name", "Название локации:");
        RU.put("dialog.save", "Сохранить");
        RU.put("dialog.cancel", "Отмена");
        RU.put("dialog.error", "Ошибка ввода");
        CS.put("dialog.add.title", "Přidat skupinu");
        CS.put("dialog.add.header", "Zadejte údaje nové skupiny");
        CS.put("dialog.edit.title", "Upravit skupinu");
        CS.put("dialog.edit.header", "Upravte údaje skupiny");
        CS.put("dialog.name", "Název:");
        CS.put("dialog.x", "X (≤225):");
        CS.put("dialog.y", "Y:");
        CS.put("dialog.students", "Studenti (>0):");
        CS.put("dialog.expelled", "Vyloučeni (>0):");
        CS.put("dialog.form", "Forma:");
        CS.put("dialog.semester", "Semestr:");
        CS.put("dialog.admin_section", "SPRÁVCE");
        CS.put("dialog.admin_name", "Jméno správce:");
        CS.put("dialog.weight", "Váha (nepov.):");
        CS.put("dialog.eye_color", "Barva očí (GREEN/RED/WHITE/BROWN):");
        CS.put("dialog.hair_color", "Barva vlasů (GREEN/BLACK/YELLOW/BROWN):");
        CS.put("dialog.nation", "Země (GERMANY/FRANCE/INDIA/SOUTH_KOREA):");
        CS.put("dialog.loc_section", "LOKACE");
        CS.put("dialog.loc_x", "Loc X:");
        CS.put("dialog.loc_y", "Loc Y:");
        CS.put("dialog.loc_z", "Loc Z:");
        CS.put("dialog.loc_name", "Název lokace:");
        CS.put("dialog.save", "Uložit");
        CS.put("dialog.cancel", "Zrušit");
        CS.put("dialog.error", "Chyba vstupu");
        DA.put("dialog.add.title", "Tilføj gruppe");
        DA.put("dialog.add.header", "Indtast data for ny gruppe");
        DA.put("dialog.edit.title", "Rediger gruppe");
        DA.put("dialog.edit.header", "Rediger gruppedata");
        DA.put("dialog.name", "Navn:");
        DA.put("dialog.x", "X (≤225):");
        DA.put("dialog.y", "Y:");
        DA.put("dialog.students", "Studerende (>0):");
        DA.put("dialog.expelled", "Bortvist (>0):");
        DA.put("dialog.form", "Form:");
        DA.put("dialog.semester", "Semester:");
        DA.put("dialog.admin_section", "ADMINISTRATOR");
        DA.put("dialog.admin_name", "Admin navn:");
        DA.put("dialog.weight", "Vægt (valgfri):");
        DA.put("dialog.eye_color", "Øjenfarve (GREEN/RED/WHITE/BROWN):");
        DA.put("dialog.hair_color", "Hårfarve (GREEN/BLACK/YELLOW/BROWN):");
        DA.put("dialog.nation", "Land (GERMANY/FRANCE/INDIA/SOUTH_KOREA):");
        DA.put("dialog.loc_section", "LOKATION");
        DA.put("dialog.loc_x", "Loc X:");
        DA.put("dialog.loc_y", "Loc Y:");
        DA.put("dialog.loc_z", "Loc Z:");
        DA.put("dialog.loc_name", "Lokationsnavn:");
        DA.put("dialog.save", "Gem");
        DA.put("dialog.cancel", "Annuller");
        DA.put("dialog.error", "Input fejl");
        ES_CO.put("dialog.add.title", "Agregar grupo");
        ES_CO.put("dialog.add.header", "Ingrese los datos del nuevo grupo");
        ES_CO.put("dialog.edit.title", "Modificar grupo");
        ES_CO.put("dialog.edit.header", "Modifique los datos del grupo");
        ES_CO.put("dialog.name", "Nombre:");
        ES_CO.put("dialog.x", "X (≤225):");
        ES_CO.put("dialog.y", "Y:");
        ES_CO.put("dialog.students", "Estudiantes (>0):");
        ES_CO.put("dialog.expelled", "Expulsados (>0):");
        ES_CO.put("dialog.form", "Forma:");
        ES_CO.put("dialog.semester", "Semestre:");
        ES_CO.put("dialog.admin_section", "ADMINISTRADOR");
        ES_CO.put("dialog.admin_name", "Nombre del admin:");
        ES_CO.put("dialog.weight", "Peso (opcional):");
        ES_CO.put("dialog.eye_color", "Color de ojos (GREEN/RED/WHITE/BROWN):");
        ES_CO.put("dialog.hair_color", "Color de cabello (GREEN/BLACK/YELLOW/BROWN):");
        ES_CO.put("dialog.nation", "País (GERMANY/FRANCE/INDIA/SOUTH_KOREA):");
        ES_CO.put("dialog.loc_section", "UBICACIÓN");
        ES_CO.put("dialog.loc_x", "Loc X:");
        ES_CO.put("dialog.loc_y", "Loc Y:");
        ES_CO.put("dialog.loc_z", "Loc Z:");
        ES_CO.put("dialog.loc_name", "Nombre de ubicación:");
        ES_CO.put("dialog.save", "Guardar");
        ES_CO.put("dialog.cancel", "Cancelar");
        ES_CO.put("dialog.error", "Error de entrada");
        RU.put("map.title", "Карта коллекции");
        RU.put("map.refresh", "Обновить");
        RU.put("map.page", "Страница %d из %d");
        RU.put("map.click_hint", "Кликните по домику для информации");
        RU.put("map.house.title", "Дом");
        RU.put("map.house.info", "ID: %d\nНазвание: %s\nX: %.0f Y: %d\nСтудентов: %d\nОтчислены: %d\nФорма: %s\nАдмин: %s");
        RU.put("map.house.edit", "Изменить");
        RU.put("map.house.delete", "Удалить");
        RU.put("map.house.close", "Закрыть");
        RU.put("map.house.confirm_delete", "Удалить объект");
        CS.put("map.title", "Mapa kolekce");
        CS.put("map.refresh", "Obnovit");
        CS.put("map.page", "Strana %d z %d");
        CS.put("map.click_hint", "Klikněte na domek pro informace");
        CS.put("map.house.title", "Dům");
        CS.put("map.house.info", "ID: %d\nNázev: %s\nX: %.0f Y: %d\nStudenti: %d\nVyloučeni: %d\nForma: %s\nSprávce: %s");
        CS.put("map.house.edit", "Upravit");
        CS.put("map.house.delete", "Odstranit");
        CS.put("map.house.close", "Zavřít");
        CS.put("map.house.confirm_delete", "Odstranit objekt");
        DA.put("map.title", "Kort over samling");
        DA.put("map.refresh", "Opdater");
        DA.put("map.page", "Side %d af %d");
        DA.put("map.click_hint", "Klik på et hus for information");
        DA.put("map.house.title", "Hus");
        DA.put("map.house.info", "ID: %d\nNavn: %s\nX: %.0f Y: %d\nStuderende: %d\nBortvist: %d\nForm: %s\nAdmin: %s");
        DA.put("map.house.edit", "Rediger");
        DA.put("map.house.delete", "Slet");
        DA.put("map.house.close", "Luk");
        DA.put("map.house.confirm_delete", "Slet objekt");
        ES_CO.put("map.title", "Mapa de colección");
        ES_CO.put("map.refresh", "Actualizar");
        ES_CO.put("map.page", "Página %d de %d");
        ES_CO.put("map.click_hint", "Haga clic en una casa para información");
        ES_CO.put("map.house.title", "Casa");
        ES_CO.put("map.house.info", "ID: %d\nNombre: %s\nX: %.0f Y: %d\nEstudiantes: %d\nExpulsados: %d\nForma: %s\nAdmin: %s");
        ES_CO.put("map.house.edit", "Modificar");
        ES_CO.put("map.house.delete", "Eliminar");
        ES_CO.put("map.house.close", "Cerrar");
        ES_CO.put("map.house.confirm_delete", "Eliminar objeto");
    }
    LocalizationManager() {
        currentLocale = new Locale("ru");
        currentLocation = RU;
    }
    public static LocalizationManager getInstance() {
        if (instance == null) {
            instance = new LocalizationManager();
        }
        return instance;
    }
    public String get(String key) {
        return currentLocation.getOrDefault(key,  key);
    }
    public String get(String key, Object... args) {
        String template = currentLocation.getOrDefault(key, key);
        return String.format(template, args);
    }
    public void setLocale(Locale locale) {
        this.currentLocale = locale;
        String lang = locale.getLanguage();
        String country = locale.getCountry();
        if ("es".equals(lang) && "CO".equals(country)) {
            currentLocation = ES_CO;
        } else {
            switch (lang) {
                case "ru": currentLocation = RU;
                break;
                case "cs": currentLocation= CS;
                break;
                case "da": currentLocation = DA;
                break;
                default: currentLocation = RU;
            }
        }
    }
}